import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import { brotliCompressSync, constants } from "node:zlib";
import test from "node:test";

const publicPages = [
  "index.html",
  "about.html",
  "work.html",
  "skills.html",
  "resume.html",
  "contact.html",
];

const readText = (file) => readFile(file, "utf8");

function fontPreloads(html) {
  return [
    ...html.matchAll(/<link\b[^>]*rel="preload"[^>]*as="font"[^>]*>/gi),
  ].map(([tag]) => tag);
}

test("public pages preload only the fonts they use above the fold", async () => {
  for (const file of publicPages) {
    const html = await readText(file);
    const preloads = fontPreloads(html);

    /*
      Playfair upright sets every heading and the monogram, all above the fold,
      so each page preloads it. The italic is used in one place - the emphasised
      phrase in the home hero - so only index.html pays for it.
    */
    const serifUpright = preloads.filter((tag) =>
      tag.includes("fonts/PlayfairDisplay-Regular.woff2"),
    );
    const serifItalic = preloads.filter((tag) =>
      tag.includes("fonts/PlayfairDisplay-Italic.woff2"),
    );

    assert.equal(serifUpright.length, 1, `${file}: serif upright preload`);
    assert.match(serifUpright[0], /type="font\/woff2"/);
    assert.match(serifUpright[0], /\bcrossorigin\b/);
    assert.equal(
      serifItalic.length,
      file === "index.html" ? 1 : 0,
      `${file}: serif italic preload`,
    );

    /*
      Two faces and no more. Both decorative fonts are gone - each existed for a
      single element and cost 287KB between them - and this catches one being
      quietly reintroduced.
    */
    assert.equal(
      preloads.length,
      file === "index.html" ? 2 : 1,
      `${file}: unexpected font preload`,
    );
  }
});

/*
  Text assets are budgeted on their compressed size, because that is what a
  visitor downloads - CloudFront serves them brotli-encoded, and the workflow
  asserts that compression stays on.

  The raw budget this replaces had been raised nine times, from 50KB to 66KB.
  Every raise had a real cause and the sheet was audited for dead rules each
  time, but a number that only ever moves upward is not catching anything: a
  paragraph of comment moved it as much as a new component did. Compressed, a
  comment costs almost nothing and a genuinely new block still shows.

  Quality 11 for a stable measurement. CloudFront compresses on the fly at a
  lower level, so the real transfer is a little larger; this figure is for
  comparing one commit against the next, not for predicting bandwidth.

  The ceiling is set roughly 600 bytes above where the sheet sits, which was
  measured rather than guessed: the architecture diagram - a genuinely new
  component at 3.3KB raw - costs 773 bytes compressed, the request-replay
  pulse drawn on top of it costs another 388, and colour-coding that pulse to
  the route it replays plus the DynamoDB arrival ring cost 460 more. So one
  more component trips this and asks for a look, while editing a comment does
  not move it.

  architecture-animation.js gets the same treatment on its own budget below:
  measured at 625 bytes, ceiling set just above it rather than at a round
  guess.
*/
const compressedSize = async (file) =>
  brotliCompressSync(await readFile(file), {
    params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
  }).length;

test("text assets stay within their compressed size budgets", async () => {
  const budgets = [
    { file: "styles.css", maximumBytes: 17_300 },
    { file: "visitor-counter.js", maximumBytes: 2_000 },
    { file: "architecture-animation.js", maximumBytes: 1_200 },
  ];

  for (const budget of budgets) {
    const size = await compressedSize(budget.file);

    assert.ok(
      size <= budget.maximumBytes,
      `${budget.file} is ${size} bytes brotli-compressed; budget is ${budget.maximumBytes}`,
    );
  }
});

test("binary assets stay within their size budgets", async () => {
  const budgets = [
    /*
      The six Open Graph cards, generated by scripts/social-cards.mjs. They land
      around 380KB each at 2400x1260 - the previous hand-made card was 687KB at
      a quarter of the pixels. PNG is already compressed, so these are budgeted
      raw; 450KB catches one that stopped compressing properly.
    */
    { file: "social-preview.png", maximumBytes: 450_000 },
    { file: "social-work.png", maximumBytes: 450_000 },
    { file: "social-skills.png", maximumBytes: 450_000 },
    { file: "social-resume.png", maximumBytes: 450_000 },
    { file: "social-about.png", maximumBytes: 450_000 },
    { file: "social-contact.png", maximumBytes: 450_000 },

    /*
      Latin subsets, not the full faces - those are around 180KB each. If either
      of these grows past 30KB it means a wider subset was swapped in, which is
      worth noticing rather than absorbing.
    */
    { file: "fonts/PlayfairDisplay-Regular.woff2", maximumBytes: 30_000 },
    { file: "fonts/PlayfairDisplay-Italic.woff2", maximumBytes: 30_000 },
  ];

  for (const budget of budgets) {
    const file = await stat(budget.file);

    assert.ok(
      file.size <= budget.maximumBytes,
      `${budget.file} is ${file.size} bytes; budget is ${budget.maximumBytes}`,
    );
  }
});

test("CloudFront compression remains enabled", async () => {
  const terraform = await readText("infra/cloudfront.tf");

  assert.match(
    terraform,
    /default_cache_behavior\s*\{[\s\S]*?compress\s*=\s*true[\s\S]*?\}/,
  );
});
