import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";

const publicPages = [
  "index.html",
  "about.html",
  "work.html",
  "skills.html",
  "resume.html",
  "contact.html",
];

const readText = (file) => readFile(file, "utf8");

function fontPreloads(html) {
  return [...html.matchAll(/<link\b[^>]*rel="preload"[^>]*as="font"[^>]*>/gi)].map(
    ([tag]) => tag,
  );
}

test("public pages preload only the fonts they use above the fold", async () => {
  for (const file of publicPages) {
    const html = await readText(file);
    const preloads = fontPreloads(html);

    /*
      Playfair upright sets every heading and the monogram, all above the fold,
      so each page preloads it. The italic is used in one place - the emphasised
      phrase in the home hero - so only index.html pays for it.
    */
    const serifUpright = preloads.filter((tag) =>
      tag.includes("fonts/PlayfairDisplay-Regular.woff2"),
    );
    const serifItalic = preloads.filter((tag) =>
      tag.includes("fonts/PlayfairDisplay-Italic.woff2"),
    );

    assert.equal(serifUpright.length, 1, `${file}: serif upright preload`);
    assert.match(serifUpright[0], /type="font\/woff2"/);
    assert.match(serifUpright[0], /\bcrossorigin\b/);
    assert.equal(
      serifItalic.length,
      file === "index.html" ? 1 : 0,
      `${file}: serif italic preload`,
    );

    /*
      Two faces and no more. Both decorative fonts are gone - each existed for a
      single element and cost 287KB between them - and this catches one being
      quietly reintroduced.
    */
    assert.equal(
      preloads.length,
      file === "index.html" ? 2 : 1,
      `${file}: unexpected font preload`,
    );
  }
});

test("critical static assets stay within their size budgets", async () => {
  const budgets = [
    /*
      64,000, against an original 50,000. Each raise has paid for something
      specific: the Gilded design itself, the two Playfair @font-face blocks,
      four star planes plus their keyframes, and now the architecture diagram's
      node, flow and boundary styles, plus the card footer row.

      Before raising it this time the sheet was audited for dead rules and had
      none worth taking. The only unreferenced selectors are .tool-js,
      .tool-python, .tool-go, .tool-docker and .tool-linux - brand colours
      provisioned for technologies no project card uses yet, which is a system
      waiting to be used rather than debt.

      The sheet holds one design, not two. The rollout's duplicate rules are
      gone and 65 duplicated selectors were folded into one rule each; what
      remains is 19 selector pairs that cannot safely be folded, because an
      @media rule sits between the halves and moving declarations past a
      breakpoint silently changes which one wins.

      So a failure here is real growth rather than leftover debt - the obvious
      thing to check first is whether a new rule duplicates one further up.
    */
    { file: "styles.css", maximumBytes: 64_000 },
    { file: "visitor-counter.js", maximumBytes: 5_000 },
    /*
      The six Open Graph cards, generated by scripts/social-cards.mjs. They land
      around 380KB each at 2400x1260 - the previous hand-made card was 687KB at
      a quarter of the pixels, so this is headroom rather than a new cost. 450KB
      catches a card that stopped being compressed properly.
    */
    { file: "social-preview.png", maximumBytes: 450_000 },
    { file: "social-work.png", maximumBytes: 450_000 },
    { file: "social-skills.png", maximumBytes: 450_000 },
    { file: "social-resume.png", maximumBytes: 450_000 },
    { file: "social-about.png", maximumBytes: 450_000 },
    { file: "social-contact.png", maximumBytes: 450_000 },

    /*
      Latin subsets, not the full faces - those are around 180KB each. If either
      of these grows past 30KB it means a wider subset was swapped in, which is
      worth noticing rather than absorbing.
    */
    { file: "fonts/PlayfairDisplay-Regular.woff2", maximumBytes: 30_000 },
    { file: "fonts/PlayfairDisplay-Italic.woff2", maximumBytes: 30_000 },
  ];

  for (const budget of budgets) {
    const file = await stat(budget.file);

    assert.ok(
      file.size <= budget.maximumBytes,
      `${budget.file} is ${file.size} bytes; budget is ${budget.maximumBytes}`,
    );
  }
});

test("CloudFront compression remains enabled", async () => {
  const terraform = await readText("infra/cloudfront.tf");

  assert.match(
    terraform,
    /default_cache_behavior\s*\{[\s\S]*?compress\s*=\s*true[\s\S]*?\}/,
  );
});
